### ISSUE TITLE
Xcode 8 won't publish

### ISSUE THREAD

**Issue by zois** [pikachu987/PKCCrop#2]
I used pod to install this. Tested it and all good. Many features, pretty much everything you need. But... when I tried to publish it, XCode8 giving all the time code signing errors, due to ".o" files from that framework. Just to check, I uninstalled it and no errors. So something is wrong with the pod?

Regards

**Comment by moon4ik** [comment]
The same trouble.

**Comment by ghost** [comment]
Same

**Comment by pikachu987** [comment]
sorry... I have renewed it, so please use it again.

**Comment by prateek7031** [comment]
I am not able to upload to the Itunes store, it gives me error of code sign. Can you please help me? I have used 0.1.3 version.

**Comment by pikachu987** [comment]
Sorry. The version you are writing has a problem with the uploading of the
app store. To upload to the App Store, you need to use version 0.2.4 or
later.
Sorry.

2017-09-27 17:58 GMT+09:00 prateek7031 <notifications@github.com>:
